### ISSUE TITLE
support for display of non-sequential elements

### ISSUE THREAD

**Issue by mlinchitstest** [bwanders/dokuwiki-plugin-templatery#2]
You plugin is incompatible with things like footnotes which are not meant to be displayed inline. Have a look at the pugin macros (https://github.com/jburle/dokuwiki_plugin_macros), which does allow for the proper display of footnotes.

**Comment by mlinchitstest** [comment]
Actually it just doesn't work with named references (like the refnotes plugin). Probably not something that can be helped. Although....

**Comment by bwanders** [comment]
Unfortunately, you are correct. That is not something that can be helped.

(On the "Although..." part: one of the following needs to become true for this to be fixed in a satisfactory manner: a) someone has enough time to write and maintain a templatery-aware branch of the refnotes plugin, or b) the core DokuWiki text parser is overhauled to a different conceptual model of handling text modes and plugins. Both of which are exceedingly unlikely.)
